import Header from './components/Header.jsx'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Automatas',
  description: 'Generated by create next app',
}
const customStyle = {
  backgroundColor: '#312244'
  // Otros estilos que desees aplicar
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" style={customStyle}>
      <body className={inter.className}>
        <Header/>
          {children}
      </body>
    </html>
  )
}
